### ISSUE TITLE
How do you keep the side window from resizing?

### ISSUE THREAD

**Issue by ColinKennedy** [stevearc/aerial.nvim#267]
When using aerial.nvim, I frequently have to load files that either just have a few classes with some functions / methods or very heavy data files with very, very nested types. When dealing with the data files, I like to manually adjust the aerial window to be wider so I can see it better. But as soon as I move the cursor between the two buffers, the window snaps back to its default width. I looked through the documentation and tried changing `layout` settings but nothing seemed to disable this automated behavior. I'd like the window to just be created with whatever width I set and not change if my cursor goes in and out between the buffers. How do you do that?

See video below

https://github.com/stevearc/aerial.nvim/assets/10103049/ab7e871b-710b-4325-b2ba-bcdba5e12869

**Comment by stevearc** [comment]
I've put up a PR that addresses your immediate comment. However, there are more cases where aerial will resize. Once you start making edits to the buffer, the window will go back to its automatically-determined width. The auto-width behavior exists so that it can, within some bounds, resize to fit the longest symbol in the file. Can you tell me more about how you expect/want this to work? Do you want no autoresizing at all? Do you want autoresizing only at certain times?

**Comment by ColinKennedy** [comment]
> Do you want no autoresizing at all? 

Yes, I would like to have an option to disable auto-resizing and have the side-bar essentially act as a regular buffer. If I need auto-resizing capabilities (e.g. resizing the Vim window, etc), there's plug-ins that handle it so I don't need aerial.nvim to provide that functionality, though I can see why others might want to have the option to auto-resize without needing to install something else.

I tend to use aerial.nvim on source code files, where nesting is low but breadth is wide and on data files the the one in the video, where nesting is very deep (the .mp4 is a fairly light example, actually) but the breadth is low. In the latter case, having zero auto-resizing would be helpful so, when I encounter a really nested hierarchy, I can make the buffer wider by resizing the window myself, once.

Worth mentioning that I'm only concerned about "no resizing" with the sidebar, mostly. I use the floating window just as much and the resizing there feels natural because the floating window takes up the full screen anyway. Hope this all makes sense!

**Comment by stevearc** [comment]
I've updated the PR to add a config option that will disable the dynamic resizing, while still doing an initial dynamic sizing based on the min/max constraints and the initial symbols. Can you give it a try and see if this works for you? #269

**Comment by ColinKennedy** [comment]
Not sure whether to reply to the PR or here but I figured I should do it here just to keep the conversation in one place.

The aerial side-bar buffer stays as a single width when moving the cursor between the text buffer and the aerial buffer, which is a great improvement! One small thing remaining is that the aerial buffer will still continue to resize whenever I choose a different file in the main window. Could that also be kept static?

https://github.com/stevearc/aerial.nvim/assets/10103049/f6399da1-c427-4561-9e68-bf57c922fd28

In case it matters, here's my current plug-in configuration.

<details>

<summary>lazy.nvim configuration</summary>

```lua
{
    "stevearc/aerial.nvim",
    config = function()
        require("aerial").setup(
            {
                backends = { "lsp", "treesitter" },
                highlight_on_jump = 100,  -- Shorten the blink time to be fast
                nav = {
                    keymaps = {
                        ["<CR>"] = "actions.jump",
                        ["q"] = "actions.close",
                    },
                },
                resize_to_content = false,
            }
        )

        vim.keymap.set(
            "n",
            "<space>SS",
            ":AerialToggle<CR>",
            {desc="[S]witch [S]idebar - Open a sidebar that shows the code file's classes, functions, etc."}
        )
        vim.keymap.set(
            "n",
            "<space>SN",
            ":AerialNavToggle<CR>",
            {desc="[S]witch [N]avigation inside / outside of classes and functions."}
        )
    end,
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    cmd = { "AerialNavToggle", "AerialToggle"},
    keys = { "<space>SN", "<space>SS" } -- S as in "Summary"
}
```
</details>

**Comment by stevearc** [comment]
Okay, I _believe_ it will now do what you want. Dynamic sizing of the window when it is first opened, and thereafter it should not modify it at all.

**Comment by ColinKennedy** [comment]
I'm using commit 075b0fa however it's still showing the behavior shown previously (swapping from a flat-ish .py file to a nested .usda file resizes the side bar every time I swap file types). My configuration is still the same as above and includes `resize_to_content = false`

**Comment by ColinKennedy** [comment]
Here's a reproduction of the two files I've been using, in case you'd like to try this out yourself https://gist.github.com/ColinKennedy/220d0a76cbbe10e59234c19297275a1d

Note that you'll need a fairly recent nvim-treesitter, this commit or later e54c8873ef964c730af451fedd4490166d335e3a. And call `:TSInstall usd`

**Comment by ColinKennedy** [comment]
> Can you confirm that you're putting resize_to_content = false nested under the layout property?

Oh whoops, I'm not. that's almost definitely the reason. Will confirm later tonight

**Comment by ColinKennedy** [comment]
Confirmed working with the PR's latest commit. Thank you for adding `resize_to_content`!

**Comment by stevearc** [comment]
Great!
