### ISSUE TITLE
WIth backends set to both LSP and treesitter, it fallbacks to treesitter initially

### ISSUE THREAD

**Issue by rockyzhang24** [stevearc/aerial.nvim#68]
**Describe the bug**
First I have this setting `backends = {"lsp", "treesitter"}`. If I am correct, I think this means use LSP as the backend and fallback to treesitter if LSP is unavailable.

I opened a buffer like `init.vim` (with viml LSP server enabled), and then I open `aerial` window. `aerial` fallback to treesitter, i.e., instead of showing symbols from LSP, it only showed symbols from treesitter. To make all the symbols from LSP to be shown, I have to make some changes like inserting an empty line or deleting a char. I think the expected behavior should be that all symbols from LSP will be shown as soon as I open `aerial`. Because I already have viml LSP server enabled, it shouldn't use treesitter. 

If set `backends = {"lsp"}`, then all symbols from LSP will be shown immediately when `aerial` window is opened, i.e., no need to change text before showing the symbols. 

**System information**
- OS: macOS (the latest version)
- Neovim version: NVIM v0.7.0-dev+1274-gc1b98cfa5
- AerialInfo: 
```
Aerial Info                                                                                                                                                                                                
-----------                                                                                                                                                                                                
Filetype: vim                                                                                                                                                                                              
Configured backends:                                                                                                                                                                                       
  lsp (supported) (attached)                                                                                                                                                                               
  treesitter (supported)                                                                                                                                                                                   
  markdown (not supported) [Filetype is not markdown]                                                                                                                                                      
Show symbols: all symbols 
```

- Aerial config:
```lua
require("aerial").setup {

  -- Mappings
  on_attach = function(bufnr)
    -- Toggle aerial window
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '\\s', '<Cmd>AerialToggle!<CR>', {}) -- "s" for symbols
    -- Jump forwards/backwards
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>{', '<cmd>AerialPrev<CR>', {})
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>}', '<cmd>AerialNext<CR>', {})
    -- Jump up the tree
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>[[', '<cmd>AerialPrevUp<CR>', {})
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>]]', '<cmd>AerialNextUp<CR>', {})
    -- Fuzzy finding symbols (it respects backends and filter_kind)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<Leader>fs', '<cmd>Telescope aerial<CR>', {})
  end,

  backends = { "lsp", "treesitter", "markdown"},
  close_behavior = "auto",
  min_width = 40,
  max_width = 40,
  show_guides = true,

  -- Set it to false to display all symbols
  filter_kind = false,
}
```

**Screenshots**
I made a show demo video below

https://user-images.githubusercontent.com/11582667/159084507-d59b6c2a-f860-4f6f-ba26-4a92bcdce8f2.mov

Thank you very much.

**Comment by stevearc** [comment]
Should be fixed now. Thanks for the report!

**Comment by rockyzhang24** [comment]
Updated and the issue sill exists. 

Before this fix, this issue happened on not only the viml buffer, but on other filetype buffers such as `go`. I tested on the [fzf](https://github.com/junegunn/fzf) repo and opened `./main.go`, and I noticed this issue as well. In my post above, I just used viml buffer as an example. 

Just now I updated `aerial` and I opened `./main.go` in `fzf`, it seemed this issue was resolved for `go` buffer. However, when I tested it on `init.vim`, the issue was still there. 

Thank you.

**Comment by stevearc** [comment]
Just to confirm: you are still seeing the behavior where you have to make changes to the buffer in order to see the LSP symbols?

Because treesitter is so much faster than LSP, we do expect to see the treesitter symbols first, but the LSP symbols should take over after a second or so.

I unfortunately can't reproduce the issue anymore on any files (go, vim, etc) so I won't be able to debug it myself. The first thing you should check is that we're actually fetching the symbols here
https://github.com/stevearc/aerial.nvim/blob/7566440e339af515f47b28f9e82fe63d58883082/lua/aerial/backends/lsp/init.lua#L115

And once you confirm that, make sure the symbols callback is being called and not hitting an early return
https://github.com/stevearc/aerial.nvim/blob/7566440e339af515f47b28f9e82fe63d58883082/lua/aerial/backends/lsp/callbacks.lua#L90

**Comment by rockyzhang24** [comment]
> Just to confirm: you are still seeing the behavior where you have to make changes to the buffer in order to see the LSP symbols?

Yes, I have to make some changes (like insert a new line by `o`) to make LSP symbols to be shown, but just for `viml`. I tried `go`, `lua` and `js`, no issues there. 

> Because treesitter is so much faster than LSP, we do expect to see the treesitter symbols first, but the LSP symbols should take over after a second or so.

For `viml` buffer, I tried to open `aerial` for a while but still no LSP symbols shown, just treesitter symbols there. I did a further test for a `lua` buffer. You know in neovim the initialization of `lua` LSP server takes quite a while. I opened a `lua` buffer and then I opened `aerial` immediately. It showed "No symbols" when the LSP server was initializing and no treesitter symbols. After that, all the LSP symbols were shown.

**Comment by stevearc** [comment]
The fact that it's only the vim language server makes me suspicious. Try upgrading it to make sure you're on the latest version. Also, since I can't reproduce it locally the best I can do is give you some ideas of how to debug it yourself. Try putting some print statements in the locations mentioned in the previous comment. The results should help narrow it down a bit.

**Comment by rockyzhang24** [comment]
Okay. I will try that later. Thank you for you help. Btw, if I remove "treesitter" from `backends` and only left "lsp" in it, it worked perfectly and no any issues.

**Comment by stevearc** [comment]
Interesting. One workaround you can use for now is to specifically exclude the treesitter backend for vim files
```lua
require('aerial').setup({
  backends = {
    ['_'] = {'lsp', 'treesitter', 'markdown'},
    vim = {'lsp'},
  }
})
```

**Comment by rockyzhang24** [comment]
1. In `M.fetch_symbols()` function, what I tried is

```lua
M.fetch_symbols = function()
  vim.lsp.buf.document_symbol()
  print("hello")
end
```

And I can definitely see the output "hello" for a `vim` buffer.

2. In `M.symbol_callback` function

```lua
M.symbol_callback = function(_err, result, context, _config)
  local client_id = context.client_id
  if not result or vim.tbl_isempty(result) then
    return
  end

  print("hello")

  local bufnr = context.bufnr
  -- Don't update if there are diagnostics errors, unless config option is set
  -- or we have no symbols for this buffer
  if
    not config.lsp.update_when_errors
    and data:has_symbols(bufnr)
    and get_error_count(bufnr, client_id) > 0
  then
    return
  end

  -- Debounce this callback to avoid unnecessary re-rendering
  if results[bufnr] == nil then
    vim.defer_fn(function()
      local r = results[bufnr]
      results[bufnr] = nil
      M.handle_symbols(r, bufnr)
    end, 100)
  end
  results[bufnr] = result
end
```

I couldn't see "hello" output, so it hit the first `return`. 

Thank you.

**Comment by stevearc** [comment]
I suspect that it's a race condition in the vimls server. It could be that we request the symbols so soon after the file is opened that it's still parsing, and instead of waiting until parsing is complete it returns an empty list. If that's the case then it would be resolved by fetching the symbols slightly later.

Try replacing
https://github.com/stevearc/aerial.nvim/blob/ed25c56c3886d956cbe919f2710c0594c7021dca/lua/aerial/backends/lsp/init.lua#L115
with
```lua
vim.defer_fn(M.fetch_symbols, 10)
```

However that wouldn't explain why it works when the treesitter backend is disabled. So perhaps it's something else entirely

**Comment by rockyzhang24** [comment]
I made this change and it still didn't work. Next, I tried `100` instead of `10`, and the issue was still there. Then I changed it to `1000`. This time, treesitter symbols were shown first and then the LSP symbols were displayed immediately. I recorded a short demo below. 

https://user-images.githubusercontent.com/11582667/159634246-df990c88-efb0-400d-bdea-377c207f3337.mov

Thank you.

**Comment by rockyzhang24** [comment]
Hi @stevearc any updates for this? Thanks a lot.

**Comment by stevearc** [comment]
This is a bug in the language server. I've submitted a fix https://github.com/iamcco/vim-language-server/pull/72

**Comment by rockyzhang24** [comment]
Great. Thank you.

**Comment by rockyzhang24** [comment]
This issue was solved after your PR to vim language server was merged. Thank you very much.
I will close this.
